import { groups, cases } from './content.mjs';
import { publicDetail } from '../public-catalog.js';

export const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
export const appPath = plugin => `/apps/${encodeURIComponent(plugin.appId)}/`;
const arrow = '<span aria-hidden="true">↗</span>';
export function shell(title, active, body) {
  const nav = [['apps', '插件', '/apps/'], ['showcase', '应用案例', '/showcase/'], ['developers', '开发者', '/developers/'], ['docs', '文档', '/docs/'], ['download','下载','https://ai-board.reai.com/zh/download']];
  const brand = '<img class="brand-logo" src="/assets/reai-logo.svg" alt="" width="36" height="36"><strong>ReAI <span>Open</span></strong>';
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} · ReAI Open</title><link rel="icon" href="/assets/reai-app-icon.svg" type="image/svg+xml"><link rel="stylesheet" href="/styles.css"><link rel="stylesheet" href="/pages.css"><script src="/catalog.js" defer></script><script src="/app.js" type="module"></script></head><body><a class="skip" href="#main">跳到主要内容</a><div class="preview-bar">ReAI Open · 开放插件、文档与应用场景</div><header class="site-header wrap"><a class="brand" href="/" aria-label="ReAI Open 首页">${brand}</a><nav aria-label="主导航">${nav.map(([id, label, href]) => `<a href="${href}" ${active === id ? 'aria-current="page"' : ''}>${label}</a>`).join('')}</nav><div class="header-actions"><!--LANGUAGE_SWITCH--><a class="header-cta" href="/docs/plugin-development-v1">开始构建 ${arrow}</a></div></header><main id="main">${body}</main><footer class="wrap"><a class="brand" href="/" aria-label="ReAI Open 首页">${brand}</a><p>连接能力，也连接创造者。</p><div><a href="/apps/">插件</a><a href="/showcase/">案例</a><a href="/docs/">文档</a><span>© 2026 ReAI</span></div></footer></body></html>`;
}
const crumb = items => `<nav class="breadcrumbs" aria-label="面包屑"><a href="/">首页</a>${items.map(([name, href]) => `<span aria-hidden="true">/</span>${href ? `<a href="${href}">${esc(name)}</a>` : `<span aria-current="page">${esc(name)}</span>`}`).join('')}</nav>`;
export function pluginCard(p) {
  return `<a class="plugin-card" href="${appPath(p)}" aria-label="查看${esc(p.name)}"><div class="plugin-top"><img src="${esc(p.icon)}" alt="" width="42" height="42"><div><h3 data-source-text>${esc(p.name)}</h3><small data-source-text>${esc(p.developerName)}</small></div><span class="card-arrow" aria-hidden="true">↗</span></div><p data-source-text>${esc(p.description)}</p><div class="plugin-bottom"><span class="tag">${esc(p.label)}</span><span>查看介绍 →</span></div></a>`;
}
export function directory() {
  return shell('发现插件', 'apps', `<section class="wrap section">${crumb([['插件']])}<div class="page-heading"><p class="eyebrow">DISCOVER / YOUR TOOLBOX</p><h1>每一种工作，<br>都有新的可能。</h1><p>探索 ReAI 插件，用合适的能力完成下一步。</p></div><div class="discovery-toolbar"><div class="filters" role="group" aria-label="按类别筛选插件"><button class="filter active" data-filter="all" aria-pressed="true">全部</button>${Object.entries(groups).map(([id, name]) => `<button class="filter" data-filter="${id}" aria-pressed="false">${name}</button>`).join('')}</div><label class="search"><input id="plugin-search" type="search" aria-label="搜索插件与能力" placeholder="搜索插件与能力"><kbd>/</kbd></label></div><div id="plugin-grid" class="plugin-grid" data-full-catalog></div><p id="search-status" class="search-status" role="status" aria-live="polite"></p><noscript><p>插件索引需要启用 JavaScript；具体插件页面仍可直接打开。</p></noscript></section>`);
}
export function detail(p, catalog) {
  if (p.status === 'published') return shell(p.name,'apps',`<section class="wrap section">${crumb([['插件','/apps/'],[p.name]])}<p class="catalog-notice" data-catalog-notice role="status">公开目录快照</p><div data-public-app="${esc(p.appId)}">${publicDetail(p)}</div></section>`);
  const versionLink = `${appPath(p)}changelog/?version=${encodeURIComponent(p.version)}`;
  const related = catalog.filter(item => item.category === p.category && item.appId !== p.appId).slice(0, 3);
  const capabilities = p.capabilities.length ? p.capabilities.map(c => `<article class="capability"><h3>${esc(c.label)}</h3><p>${esc(c.detail)}</p></article>`).join('') : '<p class="muted">此插件尚未提供独立功能卡片；介绍以现有声明为准。</p>';
  const permissions = p.permissions.length ? p.permissions.map(permission => `<li><div><strong>${esc(permission.id)}</strong><span class="tag">${permission.required ? '必需' : '可选'}</span></div><p>${esc(permission.purpose)}</p></li>`).join('') : '<li><p>Manifest 未声明用户权限项。插件仍受 Host 能力和系统权限约束。</p></li>';
  const targets = p.targets.map(t => `${esc(t.platform)} · ${(t.architectures ?? []).map(esc).join(' / ')}`).join('<br>');
  return shell(p.name, 'apps', `<section class="wrap section">${crumb([['插件', '/apps/'], [p.name]])}<div class="app-layout"><div><div class="app-heading"><img src="${esc(p.icon)}" width="80" height="80" alt=""><div><p class="eyebrow">${esc(p.label)} / REAI</p><h1>${esc(p.name)}</h1><p class="app-id">${esc(p.appId)}</p></div></div><p class="app-tagline">${esc(p.description)}</p><div class="app-tabs"><a href="#overview">概览</a><a href="#permissions">权限与兼容</a><a href="${versionLink}">更新日志 ${arrow}</a></div><section id="overview" class="content-block"><p class="eyebrow">OVERVIEW</p><h2>关于这个插件</h2><p class="body-copy">${esc(p.longDescription)}</p><div class="capability-grid">${capabilities}</div></section><section id="permissions" class="content-block"><p class="eyebrow">PERMISSIONS</p><h2>用之前，知道它需要什么。</h2><ul class="permission-list">${permissions}</ul></section><section class="content-block"><h2>了解开发与交付</h2><p class="body-copy">独立插件按自己的版本构建和审核。安装前，请核对目标 Host 的兼容要求和正式发布信息。</p><a class="inline-link" href="/docs/plugin-development-v1">阅读插件开发规范 ${arrow}</a></section></div><aside class="app-facts"><p class="eyebrow">PLUGIN INFORMATION</p><dl><dt>发布者</dt><dd>ReAI 仓库插件</dd><dt>当前本地版本</dt><dd><a href="${versionLink}">${esc(p.version)} ↗</a></dd><dt>Host API 范围</dt><dd>${esc(p.hostApi)}</dd><dt>声明的平台</dt><dd>${targets}</dd><dt>版本状态</dt><dd><span class="status-pill">本地预览</span></dd></dl><p class="muted fact-note">尚未接入正式发布目录。源码版本不代表已审核、可安装或线上最新版本。</p><a class="button secondary" href="${versionLink}">查看更新日志 →</a></aside></div>${related.length ? `<section class="related content-block"><div class="section-head"><h2>继续探索</h2><a href="/apps/" class="inline-link">全部插件 ${arrow}</a></div><div class="plugin-grid">${related.map(pluginCard).join('')}</div></section>` : ''}</section>`);
}
export function changelog(p) {
  const entries = p.changelog.map(e => `<article class="release-entry" data-version="${esc(e.version)}"><h2>${esc(e.version)}</h2><span class="tag">源码文档记录 · 发布状态未核验</span><pre class="release-notes">${esc(e.notes)}</pre></article>`).join('');
  return shell(`${p.name} 更新日志`, 'apps', `<section class="wrap section narrow-page" data-public-log="${esc(p.appId)}">${crumb([['插件', '/apps/'], [p.name, appPath(p)], ['更新日志']])}<div class="page-heading"><p class="eyebrow">CHANGELOG / VERSION HISTORY</p><h1 id="public-log-title">${esc(p.name)}<br>更新日志</h1><p>每一个版本，都应该有清楚的说明。</p></div><form class="version-search" method="get"><label for="version-query">查找具体版本</label><div><input id="version-query" name="version" maxlength="128" required value="${esc(p.version)}"><button class="button primary" type="submit">查看版本 →</button></div></form><div class="version-result" data-current-version="${esc(p.version)}"><p class="eyebrow">你正在查看</p><h2 id="requested-version">${esc(p.version)}</h2><p id="version-message" role="status">此插件尚未提供公开版本日志。</p><p class="muted">版本说明将在整理完成后展示。</p></div>${entries ? `<div class="release-list">${entries}</div>` : '<div class="empty-state"><span class="empty-symbol" aria-hidden="true">＋</span><h2>更新日志还在准备中。</h2><p>这里将记录每个版本的新功能、改进和修复。</p><a href="/docs/plugin-settings-and-release-notes-v1" class="inline-link">了解版本文档规范 ↗</a></div>'}<a id="public-log-back" class="button secondary" href="${appPath(p)}">← 返回${esc(p.name)}</a></section>`);
}
export function genericDetail(appId='') {
  return shell('插件介绍','apps',`<section class="wrap section">${crumb([['插件','/apps/']])}<p class="catalog-notice" data-catalog-notice role="status">正在读取公开目录</p><div data-public-app="${esc(appId)}">${publicDetail(null)}</div></section>`);
}
export function caseCard(c) {
  return `<a class="case-card" href="/showcase/${c.slug}/"><div class="case-art ${c.className}" aria-hidden="true"><span class="paper-label">REAI / IN PRACTICE</span><div class="case-illustration">${esc(c.headline)}</div><span class="case-stamp">${c.short}</span></div><div class="case-copy"><span class="tag">${c.category} · 场景示例</span><h3>${c.title} ${arrow}</h3><p>${c.description}</p></div></a>`;
}
export function showcase() {
  return shell('应用案例', 'showcase', `<section class="wrap section">${crumb([['应用案例']])}<div class="page-heading"><p class="eyebrow">IN PRACTICE / CONNECT THE POSSIBILITIES</p><h1>好工具在一起，<br>工作就有了新方式。</h1><p>从一个任务出发，探索插件组合。以下为场景说明，尚未作为客户案例核验。</p></div><div class="case-grid expanded-cases">${cases.map(caseCard).join('')}</div></section>`);
}
export function caseDetail(c, catalog) {
  const tools = c.plugins.map(slug => catalog.find(p => p.slug === slug)).filter(Boolean);
  return shell(c.title, 'showcase', `<section class="wrap section">${crumb([['应用案例', '/showcase/'], [c.category]])}<div class="page-heading"><p class="eyebrow">${c.category} / 场景示例</p><h1>${c.title}</h1><p>${c.description}</p></div><div class="case-detail-layout"><div><div class="case-art case-detail-art ${c.className}"><div class="case-illustration">${c.headline}</div><span class="case-stamp">${c.short}</span></div><section class="content-block"><h2>从哪里开始</h2><p class="body-copy">${c.context}</p></section><section class="content-block"><h2>一步一步，把想法接起来。</h2><ol class="case-steps">${c.steps.map((step, i) => `<li><span>${String(i + 1).padStart(2, '0')}</span><p>${step}</p></li>`).join('')}</ol></section><section class="content-block"><h2>预期结果与边界</h2><p class="body-copy">${c.outcome}</p></section></div><aside><p class="eyebrow">TOOLS IN THIS SCENARIO</p><h2>用到的插件</h2><div class="case-tools">${tools.map(pluginCard).join('')}</div>${tools.length < c.plugins.length ? '<p class="muted">部分场景工具尚未在公开目录中提供。</p>' : ''}<p class="muted fact-note">说明不代表自动化能力已经接通。实际使用以插件状态、权限及验证结果为准。</p></aside></div><a class="button secondary" href="/showcase/">← 全部应用案例</a></section>`);
}
export function developers() {
  const paths = [
    ['01', '从第一个插件开始', '项目骨架、生命周期与能力边界。', 'plugin-development-v1'],
    ['02', '连接平台能力', 'SDK、Manifest 和接口合同。', 'plugin-api-reference-v1'],
    ['03', '做出一致的体验', '界面、主题、语言与设置页规范。', 'plugin-design-system-v1'],
    ['04', '准备审核与发布', '身份核对、独立打包与版本介绍。', 'plugin-submission-v1'],
  ];
  return shell('开发者', 'developers', `<section class="wrap section">${crumb([['开发者']])}<div class="developer-section developer-intro"><div><p class="eyebrow">FOR BUILDERS / MAKE SOMETHING USEFUL</p><h1>你的下一个想法，<br>可以成为一件好工具。</h1><p class="body-copy">用独立插件接入 ReAI 的能力，从本机验证开始，逐步走向审核与发布。</p><a class="button primary" href="/docs/plugin-development-v1">开始开发 ${arrow}</a></div><div class="builder-visual"><span>IDEA</span><i>↓</i><strong>Build. Test. Share.</strong><i>↓</i><span>YOUR NEXT PLUGIN</span></div></div><section class="content-block"><div class="section-head"><h2>从这里开始构建。</h2><a href="/docs/" class="inline-link">全部开发文档 ${arrow}</a></div><div class="resource-grid">${paths.map(([n, title, summary, slug]) => `<a href="/docs/${slug}" class="resource-card"><span class="step-number">${n}</span><h3>${title}</h3><p>${summary}</p><span aria-hidden="true">↗</span></a>`).join('')}</div></section><section class="builder-contract content-block"><div><p class="eyebrow">ONE PLUGIN. ITS OWN LIFECYCLE.</p><h2>版本独立，交付清楚。</h2><p class="body-copy">稳定 appId、最小权限、可重放构建和真实验证，让插件能独立迭代。官方插件同样遵循正式审核要求。</p></div><div class="contract-list"><a href="/docs/plugin-settings-and-release-notes-v1">设置页、版本与关于入口 ${arrow}</a><a href="/docs/plugin-i18n-v1">中英文语言包规范 ${arrow}</a><a href="/docs/lifecycle-hooks-v1">插件生命周期 ${arrow}</a><a href="/apps/">探索已有插件 ${arrow}</a></div></section><p class="migration-note">开发文档已在此站提供，原文档入口继续可用： <a href="https://ai-board.reai.com/docs/" target="_blank" rel="noopener">ai-board.reai.com/docs ↗</a>。</p></section>`);
}
export function notFound() {
  return shell('页面未找到', '', '<section class="wrap section narrow-page"><div class="empty-state"><p class="eyebrow">404 / NOT FOUND</p><h1>这个页面还没有找到。</h1><p>链接可能已变化。你可以回到首页，或继续发现插件。</p><a class="button primary" href="/">返回首页 →</a><a class="button secondary" href="/apps/">探索插件</a></div></section>');
}
