import matrix from "@reai/app-contract/host-support-matrix.json";
import hostCodes from "./voice-host-error-codes.json";

/**
 * 可以导出（进复制诊断、浮层、落盘）的错误码登记表（§6.0 #waiting-failure-minimum 白名单）。
 *
 * 码是否能出现在旁人可见或会离开本机的地方，按**值**判断，不按长相判断：只有这里登记过的码
 * 才导出；没登记的码只留在内存原文里（Voice 页「展开原始信息」可见），复制文本写「未登记，已省略」。
 * 来源：平台合同 `host-support-matrix.json` 的稳定错误码 + Host 常量码快照（`voice-host-error-codes.json`）
 * + 插件自己抛出 / 识别的码与 Host 回的小写枚举 + 浏览器标准异常名。插件源码里新出现的码要在这里登记
 * （`voice-error-codes.test.ts` 会扫源码提醒）；Host 新增的码没登记时只会显示「未登记，已省略」，不会外流。
 */
const PLUGIN_AND_HOST_CODES = [
  "AGENT_ATTACHMENT_SCENE_UNSUPPORTED", "AGENT_ATTACHMENT_BINDING_CHANGED", "AGENT_ATTACHMENT_CACHE_CAPACITY", "AGENT_ATTACHMENT_CACHE_CORRUPT", "AGENT_ATTACHMENT_CACHE_SAVE_FAILED", "AGENT_ATTACHMENT_CONTENT_INVALID", "AGENT_ATTACHMENT_INCOMPLETE", "AGENT_ATTACHMENT_INPUT_UNSUPPORTED", "AGENT_ATTACHMENT_LEASE_EXPIRED", "AGENT_ATTACHMENT_READER_DISABLED", "AGENT_ATTACHMENT_TOO_LARGE", "AGENT_ATTACHMENT_UNCONFIRMED", "AGENT_ATTACHMENT_UNSUPPORTED",
  // 附件准备与文档提取：固定错误码，不含文件名、内容或解析器原始异常。
  "VOICE_ATTACHMENT_SCENE_UNSUPPORTED", "VOICE_ATTACHMENT_MODEL_UNCONFIRMED", "VOICE_ATTACHMENT_EMPTY", "VOICE_ATTACHMENT_TOO_LARGE", "VOICE_ATTACHMENT_NAME_INVALID", "VOICE_ATTACHMENT_READ_FAILED",
  "VOICE_ATTACHMENT_ENCODING_UNSUPPORTED", "VOICE_ATTACHMENT_BINARY_UNSUPPORTED", "VOICE_ATTACHMENT_EXTRACTION_REQUIRED",
  "VOICE_ATTACHMENT_COUNT_EXCEEDED", "VOICE_ATTACHMENT_TURN_TOO_LARGE", "VOICE_ATTACHMENT_DOCUMENT_INVALID",
  "VOICE_ATTACHMENT_DOCUMENT_LIMIT", "VOICE_ATTACHMENT_DOCUMENT_NO_TEXT", "VOICE_ATTACHMENT_DOCUMENT_TIMEOUT",
  "VOICE_ATTACHMENT_DOCUMENT_UNAVAILABLE", "VOICE_ATTACHMENT_DOCUMENT_ENCRYPTED", "VOICE_ATTACHMENT_DOCUMENT_TOO_LARGE",
  // 插件自己抛出或按码识别的（不带命名空间的写法；`com.reai.voice/` 前缀另行接受）。
  "AGENTS_IM_OPEN_FAILED", "AGENT_CANCELLED", "AGENT_EMPTY_RESPONSE", "AGENT_KILLED", "AGENT_PENDING_CAPACITY",
  "AGENT_PENDING_IDENTITY_CONFLICT", "AGENT_PENDING_NOT_FOUND", "AGENT_PENDING_STORAGE_CONFLICT", "AGENT_RECEIPT_UNKNOWN",
  "AGENT_RESULT_IDENTITY_MISMATCH", "AGENT_RESULT_UNAVAILABLE", "AGENT_SCOPE_UNAVAILABLE", "AGENT_TIMEOUT", "AGENT_WAIT_TIMEOUT",
  "AGENT_RESULT_EXPIRED",
  // C-AC 覆盖层/功能合同（Host 1.23，插件 Agent 配置生效链）。
  "AGENT_PLUGIN_CONFIG_CORRUPT", "AGENT_PLUGIN_CONFIG_WRITE_FAILED",
  "AGENT_PLUGIN_CONFIG_INVALID", "AGENT_PLUGIN_CONFIG_UNREADABLE", "AGENT_PLUGIN_CONFIG_VERSION_INVALID",
  "AGENT_FEATURE_NOT_DECLARED",
  // 技能目录（PR5）：扫描/展开的稳定错误码。
  "AGENT_SKILL_DIR_UNREADABLE", "AGENT_SKILL_DIR_NOT_DIR", "AGENT_SKILL_DIR_SYMLINK",
  "AGENT_SKILL_DIR_TOO_LARGE", "AGENT_SKILL_NOT_FOUND", "AGENT_SKILL_OVER_LIMIT",
  "AGENT_SKILL_ID_INVALID",
  "AGENT_SKILL_ID_COLLISION",
  "AGENT_FEATURE_PROMPT_DRIFT", "AGENT_FEATURE_PARAM_MISSING", "AGENT_FEATURE_TOOL_OUT_OF_BASE",
  "AI_MODEL_PERMISSION_REQUIRED", "AI_SESSION_CHANGED", "BRIDGE_DENIED", "CLIPBOARD_UNAVAILABLE",
  "CLOUD_CANCELLED", "CLOUD_MODEL_SELECTION_REQUIRED", "CLOUD_SESSION_CHANGED", "CLOUD_TRANSCRIBE_FAILED",
  "CONTEXT_NOT_TRANSCRIBED", "CONTEXT_SEGMENT_NOT_FOUND", "DIGEST_BUSY", "DIGEST_DISABLED", "DIGEST_EMPTY", "DIGEST_FAILED",
  "DIGEST_NOT_READY", "DIGEST_NO_SOURCE", "DIGEST_TIMEOUT", "DSH_ENGINE", "DSH_ENGINE_UNAVAILABLE", "DSH_INVALID_REQUEST",
  "DSH_KILLED", "DSH_LOGIN_REQUIRED", "DSH_NOT_GRANTED", "DSH_SEND_FAILED", "DSH_SESSION_STALE", "DSH_TIMEOUT",
  "NO_ACTIVE_VIEW", "OAUTH_SESSION_CHANGED", "PLUGIN_OAUTH_REAUTH_REQUIRED", "POLISH_EMPTY", "POLISH_FAILED",
  "POLISH_IMPLAUSIBLE", "POLISH_RESPONSE_INVALID", "POLISH_TIMEOUT", "SERVICE_PROVIDER_FAILED", "SUMMARY_BUSY",
  "TRANSLATION_CHAT_REPLY", "TRANSLATION_WRONG_LANGUAGE",
  "SUMMARY_CONSENT_REQUIRED", "SUMMARY_FAILED", "SUMMARY_SAVE_FAILED", "SURFACE_INIT_FAILED", "VOICE_CAPTURE_CLEANUP_REQUIRED",
  "VOICE_CAPTURE_INTERRUPTED", "VOICE_CAPTURE_NOT_STARTED", "VOICE_CAPTURE_SESSION_CHANGED", "VOICE_COMMAND_HISTORY_SAVE_FAILED",
  "VOICE_COMMAND_INTERRUPTED", "VOICE_COMMAND_NO_SPEECH", "VOICE_CONVERSATION_MISSING", "VOICE_EMPTY_FOLLOW_UP",
  "VOICE_EMPTY_TRANSCRIPT", "VOICE_EMPTY_UTTERANCE", "VOICE_HOST_UPGRADE_REQUIRED", "VOICE_OPERATION_IN_PROGRESS", "VOICE_RECORDS_CLEAR_INCOMPLETE",
  "VOICE_REQUEST_CLOCK_CHANGED", "VOICE_REQUEST_EXPIRED", "VOICE_REQUEST_IDENTITY_REQUIRED", "VOICE_REQUEST_INVALID",
  "VOICE_REQUEST_INVALID_RESULT", "VOICE_REQUEST_REPLAYED", "VOICE_REQUEST_STORAGE_UNAVAILABLE", "VOICE_SETUP_CLOUD_UNAVAILABLE",
  "VOICE_SETUP_ROLLBACK_FAILED", "VOICE_START_CANCELLED", "VOICE_START_TIMEOUT", "VOICE_STATUS_REFRESH_TIMEOUT",
  // Host 系统任务与 Voice 相关接口回的码。
  "SYSTEM_TASK_BUSY", "SYSTEM_TASK_CANCELLED", "SYSTEM_TASK_INTERRUPTED", "SYSTEM_TASK_NAVIGATION_ACK_EXPIRED",
  "SYSTEM_TASK_NAVIGATION_BLOCKED", "SYSTEM_TASK_NOT_FOUND", "SYSTEM_TASK_RATE_LIMITED", "SYSTEM_TASK_RETURN_NAVIGATION_BLOCKED",
  "SYSTEM_TASK_RETURN_PENDING", "SYSTEM_TASK_RETURN_UNAVAILABLE", "SYSTEM_TASK_STATE_CONFLICT", "SYSTEM_TASK_STATUS_UNAVAILABLE",
  "SYSTEM_TASK_VISIBLE_SURFACE_REQUIRED", "VOICE_ACCOUNT_UNAVAILABLE", "VOICE_BUSY", "VOICE_CANCELLED", "VOICE_COMMAND_CANCELLED",
  "VOICE_COMMAND_CONFIG_SAVE_FAILED", "VOICE_COMMAND_FAILED", "VOICE_COMMAND_FORBIDDEN", "VOICE_COMMAND_LOGIN_REQUIRED",
  "VOICE_COMMAND_NOT_CONFIGURED", "VOICE_COMMAND_PAYMENT_REQUIRED", "VOICE_COMMAND_RATE_LIMITED", "VOICE_COMMAND_RESPONSE_INVALID",
  "VOICE_COMMAND_TIMEOUT", "VOICE_COMMAND_UNAUTHORIZED", "VOICE_CONFIG_SAVE_FAILED", "VOICE_ENDPOINT_ENUMERATION_FAILED",
  "VOICE_FIRMWARE_TOO_OLD", "VOICE_FIRMWARE_UNKNOWN", "VOICE_INPUT_SESSIONS_LIST_FAILED", "VOICE_INPUT_SESSION_NOT_PENDING",
  "VOICE_INPUT_SESSION_UPDATE_FAILED", "VOICE_MIC_PERMISSION_REQUIRED", "VOICE_MODEL_IMMUTABLE", "VOICE_MODEL_UNAVAILABLE",
  "VOICE_NOT_GRANTED", "VOICE_NOT_LISTENING", "VOICE_NOT_OWNER", "VOICE_PERMISSION_CHECK_FAILED", "VOICE_PERMISSION_REQUEST_FAILED",
  "VOICE_RECOGNIZER_FAILED", "VOICE_RECORDINGS_LIST_FAILED", "VOICE_RECORDING_CONTROL_FAILED", "VOICE_RECORDING_CORRUPT",
  "VOICE_RECORDING_DELETE_FAILED", "VOICE_RECORDING_NOT_FOUND", "VOICE_RECORDING_READ_FAILED", "VOICE_RECORDING_RETRANSCRIBE_FAILED",
  "VOICE_RECORDING_SUMMARY_FAILED", "VOICE_RECORDING_TOKEN_FAILED", "VOICE_REPLAY_CACHE_CLEAR_FAILED", "VOICE_REPLAY_CACHE_READ_FAILED",
  "VOICE_REQUEST_SESSION_CHANGED", "VOICE_REQUEST_STALE", "VOICE_SERIALIZE_FAILED", "VOICE_SESSION_INVALID", "VOICE_SOURCE_UNAVAILABLE",
  "VOICE_STT_FAILED", "VOICE_SYSTEM_MIC_RELEASE_FAILED", "VOICE_TIMELINE_CLEAR_FAILED", "VOICE_TIMELINE_CONTROL_FAILED",
  "VOICE_TIMELINE_EXPORT_FAILED", "VOICE_TIMELINE_GRANT_DENIED", "VOICE_TIMELINE_NO_AUDIO", "VOICE_TIMELINE_NO_SPEECH",
  "VOICE_TIMELINE_PROMOTION_FAILED", "VOICE_TIMELINE_RANGE_INVALID", "VOICE_TIMELINE_TARGET_GONE",
  // 写回回执类别、音源问题、时间线不可用原因、联网工具失败类别（小写枚举）。
  "accessibility_permission_required", "voice_deliver_permission_required", "voice_deliver_unavailable", "expired",
  "focus_changed", "own_overlay_focused", "no_input_target", "not_editable", "not_received", "unknown_target", "denied",
  "insert_failed", "polish_failed", "disconnected", "firmware_too_old", "firmware_unknown", "source_unavailable",
  "route_reconciling", "board_disconnected", "browser_plugin_required", "browser_plugin_declined", "web_access_not_logged_in",
  "web_access_scope_unavailable", "web_access_project_unavailable", "web_access_rate_limited", "web_access_insufficient_credits",
  "web_access_subscription_required", "web_access_unavailable",
  // 浏览器标准异常名（剪贴板、回听）。
  "AbortError", "NotAllowedError", "NotSupportedError", "NotFoundError", "SecurityError", "InvalidStateError", "TimeoutError",
  "NetworkError", "EncodingError", "DataError", "QuotaExceededError",
] as const;

const REGISTERED: ReadonlySet<string> = new Set<string>([
  ...matrix.stableErrors,
  ...matrix.pluginPermissions.stableErrors,
  ...hostCodes.codes,
  ...PLUGIN_AND_HOST_CODES,
]);
const PLUGIN_NAMESPACE = "com.reai.voice/";
/** 回听的 MediaError 只有 1–4 四个标准码。 */
const MEDIA_ERROR = /^MediaError code [1-4]$/;

/** 登记过的码原样返回；其余（含形似码的凭据、用户说的话）一律 undefined。 */
export function registeredErrorCode(value: unknown): string | undefined {
  if (typeof value !== "string") return undefined;
  const code = value.trim();
  if (REGISTERED.has(code) || MEDIA_ERROR.test(code)) return code;
  if (code.startsWith(PLUGIN_NAMESPACE) && REGISTERED.has(code.slice(PLUGIN_NAMESPACE.length))) return code;
  return undefined;
}
