import { expect, test } from "bun:test";
import { GlobalRegistrator } from "@happy-dom/global-registrator";
import { MockHost } from "@reai/app-test/v1";
import manifest from "../app.manifest.json";
import app from "../src/app";
if (!globalThis.document) GlobalRegistrator.register();
const until = async (condition: () => boolean) => { for (let i = 0; i < 100; i++) { if (condition()) return; await new Promise(r => setTimeout(r, 5)); } throw Error("UI did not settle"); };

test("real entry uses planned service, binds principals, scopes writes and updates visible quota", async () => {
  const host = new MockHost({ manifest, loadApp: async () => ({ default: app }), createRoot: () => document.createElement("div") });
  host.serviceHandler = () => ({ demands: [{ id: "real-demand", title: "Local requirement", body: "Acceptance goal", status: "planned" }] });
  let principal: unknown, issued = 0;
  host.gatewayIssueHandler = scope => { principal = (scope as { principal: unknown }).principal; return { id: `connection-${++issued}`, endpoint: "http://127.0.0.1:4321/v1/call", token: "a".repeat(64) }; };
  await host.installAndEnable();
  const surface = await host.openSurface("main"), root = surface.root!;
  await until(() => !!root.querySelector("[data-task]"));
  root.querySelector<HTMLButtonElement>('[data-tab="roles"]')!.click();
  root.querySelector<HTMLButtonElement>('[data-new-agent]')!.click();
  await until(() => !!root.querySelector("[data-connection]"));
  const id = (principal as { agentId: string }).agentId;
  expect(id).toStartWith("O-");
  const caller = { appId: manifest.appId, surfaceMountId: "gateway-one", runtimeSessionId: "gateway-one", external: { id: "host-issued", principal: { agentId: id } } };
  const service = "com.reai.code-worker/agent@1";
  const denied = await host.invokeService(service, "invoke", { kind: "read", actorId: id });
  expect(denied.ok).toBe(false);
  const read = await host.invokeService(service, "invoke", { kind: "read" }, caller);
  expect(read.ok).toBe(true);
  const snapshot = read.output as { revision: number; claimable: { id: string }[] };
  const result = await host.invokeService(service, "invoke", { kind: "act", action: { requestId: "claim", expectedRevision: snapshot.revision, operation: "claim", payload: { taskId: snapshot.claimable[0].id } } }, caller);
  expect(result.ok).toBe(true);
  const other = await host.invokeService(service, "invoke", { kind: "read" }, { ...caller, external: { id: "another", principal: { agentId: "made-up" } } });
  expect(other.ok).toBe(false);
  let serial = 0;
  const act = async (identity: typeof caller, operation: string, payload: object) => {
    const state = await host.invokeService(service, "invoke", { kind: "read" }, caller);
    const action = { requestId: `life-${++serial}`, expectedRevision: (state.output as {revision:number}).revision, operation, payload };
    return { action, result: await host.invokeService(service, "invoke", { kind: "act", action }, identity) };
  };
  const taskId = snapshot.claimable[0].id;
  const childAdded = await act(caller, "addChild", { taskId, title: "Lifecycle", acceptance: "Real execution receipt" });
  const childId = (childAdded.result.output as {projection:{children:{id:string}[]}}).projection.children[0].id;
  const assignment = await act(caller, "startWorker", { childId });
  const assigned = assignment.result.output as {projection:{children:{worker:string}[]},connection:{id:string}};
  const worker = { ...caller, external: { id: assigned.connection.id, principal: { agentId: assigned.projection.children[0].worker } } };
  expect((await act(worker, "begin", { childId })).result.ok).toBe(true);
  const ended = await act(worker, "cancel", { childId, reason: "Confirmed process exit" });
  expect(ended.result.ok).toBe(true);
  expect((await host.invokeService(service, "invoke", { kind: "read" }, worker)).ok).toBe(false);
  expect((await host.invokeService(service, "invoke", { kind: "act", action: ended.action }, worker)).ok).toBe(true);
  await host.unmountSurface(surface.surfaceMountId);
  const afterClose = await host.invokeService(service, "invoke", { kind: "read" }, caller);
  expect(afterClose.ok).toBe(true);
  expect((afterClose.output as { tasks: unknown[] }).tasks).toHaveLength(1);
  await host.disable();
});
