import type { NiChatState } from "./model";

const T = "2026-08-12T08:00:00Z";

export function createMockNiChatState(): NiChatState {
  return {
    selfProfileId: "me",
    transport: "mock",
    capabilities: ["presence.public", "status.transient", "message.stream", "interaction.answer"],
    profiles: {
      me: { id: "me", type: "user", username: "kongkang", displayName: "你", avatarText: "K" },
      "human-alice": { id: "human-alice", type: "user", username: "alice", displayName: "Alice", avatarText: "A", bio: "产品设计" },
      "agent-coder": { id: "agent-coder", type: "agent", username: "code-helper", displayName: "代码助手", avatarText: "C", bio: "通过 ni-chat 连接" },
      "agent-research": { id: "agent-research", type: "agent", username: "research-helper", displayName: "研究助手", avatarText: "R", bio: "通过 ni-chat 连接" },
      "system-ni": { id: "system-ni", type: "system", username: "ni-chat-system", displayName: "ni.chat 系统", avatarText: "N" },
      /* B6-26「在 IM 里看上下文」的落点：与 agent-ui 演示流同一身份契约
         （id cc / displayName Claude Code，SCAN_FOUND 本就列有它）。 */
      cc: { id: "cc", type: "agent", username: "claude-code", displayName: "Claude Code", avatarText: "◆", bio: "本机 CLI · ~/Projects/example-app" },
      /* 同上（B6-26）：agent-ui 演示流里带目录的任务来自 cc 与 codex 两家，
         反向入口在演示数据下每条都要有语义真实的落点。 */
      codex: { id: "codex", type: "agent", username: "codex", displayName: "Codex", avatarText: "⬡", bio: "本机 CLI · ~/Projects/example-app" },
    },
    conversations: [
      {
        id: "human-agent",
        revision: 1,
        type: "private",
        participantIds: ["me", "agent-coder"],
        lastMessagePreview: "发布说明准备好了，请确认范围",
        lastMessageAt: "2026-08-12T08:00:20Z",
        unreadCount: 1,
        needsActionCount: 1,
        pinned: true,
      },
      {
        id: "human-human",
        revision: 1,
        type: "private",
        participantIds: ["me", "human-alice"],
        lastMessagePreview: "今晚见",
        lastMessageAt: "2026-08-12T07:50:00Z",
        unreadCount: 0,
      },
      {
        id: "agent-agent",
        revision: 1,
        type: "private",
        participantIds: ["agent-coder", "agent-research"],
        title: "Agent 协作",
        lastMessagePreview: "接口证据已整理",
        lastMessageAt: "2026-08-12T07:45:00Z",
        unreadCount: 0,
      },
      {
        id: "mixed-group",
        revision: 1,
        type: "group",
        participantIds: ["me", "human-alice", "agent-coder", "agent-research"],
        title: "发布小组",
        lastMessagePreview: "Alice 提及了你",
        lastMessageAt: "2026-08-12T07:40:00Z",
        unreadCount: 2,
        muted: true,
      },
      {
        id: "system-news",
        revision: 1,
        type: "system",
        participantIds: ["system-ni"],
        title: "ni.chat 公告",
        lastMessagePreview: "系统维护窗口",
        lastMessageAt: "2026-08-12T07:30:00Z",
        unreadCount: 0,
      },
      {
        id: "human-codex",
        revision: 1,
        type: "private",
        participantIds: ["me", "codex"],
        lastMessagePreview: "价格表改版审查提了 4 条意见",
        lastMessageAt: "2026-08-12T08:10:00Z",
        unreadCount: 0,
      },
      {
        id: "human-cc",
        revision: 1,
        type: "private",
        participantIds: ["me", "cc"],
        lastMessagePreview: "发布说明的初稿写好了",
        lastMessageAt: "2026-08-12T08:05:00Z",
        unreadCount: 0,
      },
    ],
    participants: [
      { conversationId: "human-codex", profileId: "me", role: "member", joinedAt: T },
      { conversationId: "human-codex", profileId: "codex", role: "member", joinedAt: T },
      { conversationId: "human-cc", profileId: "me", role: "member", joinedAt: T },
      { conversationId: "human-cc", profileId: "cc", role: "member", joinedAt: T },
      { conversationId: "human-agent", profileId: "me", role: "member", joinedAt: T },
      { conversationId: "human-agent", profileId: "agent-coder", role: "member", joinedAt: T },
      { conversationId: "human-human", profileId: "me", role: "member", joinedAt: T },
      { conversationId: "human-human", profileId: "human-alice", role: "member", joinedAt: T },
      { conversationId: "agent-agent", profileId: "agent-coder", role: "member", joinedAt: T },
      { conversationId: "agent-agent", profileId: "agent-research", role: "member", joinedAt: T },
      { conversationId: "mixed-group", profileId: "me", role: "owner", joinedAt: T },
      { conversationId: "mixed-group", profileId: "human-alice", role: "member", joinedAt: T },
      { conversationId: "mixed-group", profileId: "agent-coder", role: "member", joinedAt: T },
      { conversationId: "mixed-group", profileId: "agent-research", role: "member", joinedAt: T },
      { conversationId: "system-news", profileId: "system-ni", role: "owner", joinedAt: T },
    ],
    messagesByConversation: {
      "human-cc": [
        {
          id: "hcc-1",
          conversationId: "human-cc",
          senderId: "me",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "写这版发布说明，范围是 App 和固件" }],
          createdAt: "2026-08-12T08:03:00Z",
        },
        {
          id: "hcc-2",
          conversationId: "human-cc",
          senderId: "cc",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "发布说明的初稿写好了，先看客户端改动与固件兼容边界这两段。" }],
          createdAt: "2026-08-12T08:05:00Z",
        },
      ],
      "human-codex": [
        {
          id: "hcd-1",
          conversationId: "human-codex",
          senderId: "codex",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "价格表改版审查完成，提了 4 条意见，主要在对比表的对齐口径。" }],
          createdAt: "2026-08-12T08:10:00Z",
        },
      ],
      "human-agent": [
        {
          id: "ha-1",
          conversationId: "human-agent",
          senderId: "me",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "帮我整理这版发布说明" }],
          createdAt: "2026-08-12T07:58:00Z",
        },
        {
          id: "ha-2",
          conversationId: "human-agent",
          senderId: "agent-coder",
          revision: 3,
          origin: "profile",
          replyTo: { messageId: "ha-1", senderLabel: "你", preview: "发布说明" },
          parts: [
            { kind: "thinking", summary: "我检查了本次版本涉及的客户端改动与兼容边界。" },
            { kind: "tool_call", name: "search_repository", status: "completed", summary: "查找发布相关改动" },
            { kind: "tool_result", name: "search_repository", status: "completed", summary: "已完成：找到 6 个相关变更" },
            { kind: "text", text: "发布说明准备好了，请确认范围。", mentions: [{ profileId: "me", label: "你" }] },
            { kind: "file", fileId: "file-release", name: "release-notes.md", mimeType: "text/markdown", sizeBytes: 4096 },
            { kind: "image", fileId: "file-cover", name: "release-cover.png", alt: "发布封面预览" },
            { kind: "audio", fileId: "file-audio", name: "voice-preview.m4a", durationSeconds: 12 },
            { kind: "video", fileId: "file-video", name: "demo.mp4", durationSeconds: 28 },
            { kind: "webpage", url: "https://example.com/release", title: "发布页面预览", description: "只显示协议提供的安全摘要" },
            { kind: "interaction_ref", interactionId: "interaction-1" },
            { kind: "unknown", originalKind: "future_canvas", safeSummary: "future_canvas" },
          ],
          createdAt: "2026-08-12T08:00:20Z",
        },
      ],
      "human-human": [
        {
          id: "hh-1",
          conversationId: "human-human",
          senderId: "human-alice",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "晚上一起确认发布页？" }],
          createdAt: "2026-08-12T07:49:00Z",
        },
      ],
      "agent-agent": [
        {
          id: "aa-1",
          conversationId: "agent-agent",
          senderId: "agent-research",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "接口证据已整理，你可以继续生成客户端摘要。" }],
          createdAt: "2026-08-12T07:45:00Z",
        },
      ],
      "mixed-group": [
        {
          id: "mg-1",
          conversationId: "mixed-group",
          senderId: "human-alice",
          revision: 1,
          origin: "profile",
          parts: [{ kind: "text", text: "封面需要再确认一下。", mentions: [{ profileId: "me", label: "你" }] }],
          createdAt: "2026-08-12T07:40:00Z",
        },
      ],
      "system-news": [
        {
          id: "sys-1",
          conversationId: "system-news",
          senderId: "system-ni",
          revision: 1,
          origin: "system",
          parts: [{ kind: "text", text: "系统维护窗口：8 月 13 日 02:00–02:15，期间消息会自动补收。" }],
          createdAt: "2026-08-12T07:30:00Z",
        },
      ],
    },
    interactions: {
      "interaction-1": {
        id: "interaction-1",
        conversationId: "human-agent",
        state: "pending",
        version: 1,
        prompt: "发布说明要包含哪些内容？",
        schema: {
          kind: "choice",
          options: [
            { id: "all", label: "App 和固件" },
            { id: "app", label: "只发 App" },
            { id: "split", label: "拆成两篇" },
          ],
        },
        eligibleResponderIds: ["me"],
        expiresAt: "2026-08-12T09:00:00Z",
      },
    },
    presenceByProfile: {
      "agent-coder": { profileId: "agent-coder", revision: 1, state: "online", expiresAt: "2026-08-12T08:10:00Z" },
      "agent-research": { profileId: "agent-research", revision: 1, state: "online", expiresAt: "2026-08-12T08:10:00Z" },
      "human-alice": { profileId: "human-alice", revision: 1, state: "offline", lastSeenAt: "2026-08-12T07:50:00Z" },
    },
    transientByConversation: {
      "human-agent": {
        conversationId: "human-agent",
        profileId: "agent-coder",
        revision: 1,
        kind: "thinking",
        expiresAt: "2026-08-12T08:01:00Z",
      },
    },
  };
}
