import { cpSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { patchPdfjsDecodedBudget } from "./pdfjs-decoded-budget-patch";
import { buildVoiceSheetjsReader } from "./sheetjs-hyperlink-guard-patch";
const root = resolve(import.meta.dir, "..");
const output = join(root, "assets/document-extraction");
mkdirSync(join(output, "pdfjs"), { recursive: true });
const pdfRoot = join(root, "node_modules/pdfjs-dist");
if (JSON.parse(readFileSync(join(pdfRoot, "package.json"), "utf8")).version !== "6.3.289") throw new Error("Pinned PDF.js package mismatch");
const upstream = readFileSync(join(pdfRoot, "legacy/build/pdf.worker.mjs"), "utf8");
const patched = patchPdfjsDecodedBudget(upstream);
const pdfBuild = await Bun.build({ entrypoints: ["voice-budget-worker.mjs"], target: "browser", format: "esm", minify: true, plugins: [{ name: "voice-pdf-budget", setup(build) { build.onResolve({ filter: /^voice-budget-worker\.mjs$/ }, () => ({ path: "voice-budget-worker.mjs", namespace: "voice-budget" })); build.onLoad({ filter: /.*/, namespace: "voice-budget" }, () => ({ contents: patched, loader: "js" })); } }] });
if (!pdfBuild.success || pdfBuild.outputs.length !== 1) throw new Error(`PDF worker build failed: ${pdfBuild.logs.join("\n")}`);
writeFileSync(join(output, "pdfjs/pdf.worker.mjs"), upstream.slice(0, upstream.indexOf("*/") + 2) + "\n" + await pdfBuild.outputs[0]!.text());
for (const directory of ["cmaps", "standard_fonts"]) cpSync(join(pdfRoot, directory), join(output, "pdfjs", directory), { recursive: true });
const xlsxRoot = join(root, "node_modules/xlsx");
if (JSON.parse(readFileSync(join(xlsxRoot, "package.json"), "utf8")).version !== "0.20.3") throw new Error("Pinned SheetJS package mismatch");
mkdirSync(join(root, "src/generated"), { recursive: true });
writeFileSync(join(root, "src/generated/sheetjs-reader.mjs"), await buildVoiceSheetjsReader(readFileSync(join(xlsxRoot, "xlsx.mjs"), "utf8")));
const proc = Bun.spawn([process.execPath, "build", "src/voice-document-worker.ts", "--outfile", "assets/document-extraction/spreadsheet.worker.mjs", "--target", "browser", "--format", "esm", "--minify"], { cwd: root, stdout: "pipe", stderr: "pipe" });
const [exitCode, stderr] = await Promise.all([proc.exited, new Response(proc.stderr).text()]);
if (exitCode) throw new Error(`Document worker build failed: ${stderr}`);
const notices = ["pdfjs-dist", "xlsx", "fflate"].map(name => `${name}\n${readFileSync(join(root, "node_modules", name, "LICENSE"), "utf8")}`);
writeFileSync(join(output, "THIRD_PARTY_LICENSES.txt"), notices.join("\n\n"));
console.log("Prepared offline PDF.js worker/fonts/CMaps and spreadsheet worker.");
